name: featExtractor Python CI/CD

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MQHOST: localhost
      MQUSER: merUser
      MQPASS: passwordMER
      MQPORT: 5672
      MNG_PORT: 15672

    steps:
    - name: Setup RabbitMQ Image
      uses: mer-team/rabbitmq-mng-action@v1.2
      with:
        RABBITMQ_USER: $MQUSER
        RABBITMQ_PASS: $MQPASS
        RABBITMQ_PORT: $MQPORT
        RABBITMQ_MNG_PORT: $MNG_PORT
        RABBITMQ_TAG: '3-management-alpine'

    - name: Checkout featExtractor Project
      uses: actions/checkout@v2

    - name: Build Local featExtractor Docker Image
      run: docker build -t featextractor:local .

    - name: Container Image Scan
      uses: azure/container-scan@v0
      with:
        image-name: featextractor:local
    
    - name: Run Local featExtractor Docker Image
      run: docker run -d -e TIME=10 -e HOST=$MQHOST -e USER=$MQUSER -e PASS=$MQPASS -e MNG_PORT=$MNG_PORT --net=host -v $GITHUB_WORKSPACE/music:/Audios featextractor:local

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '2.7'

    - name: Test with pytest
      run: |
        pip install pytest pika enum
        pytest

    - name: Dump docker logs on failure
      if: failure()
      uses: jwalton/gh-docker-logs@v1